services:
  mysql:
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: lidaning
      MYSQL_DATABASE: mymysql
    ports:
      - 3306:3306
    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    
  adminer:
    image: adminer
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql

  demo:
    build:
      context: .
      dockerfile: docker/demo/Dockerfile
    ports:
      - 80:81
    depends_on:
      - mysql
