spring:
  application:
    name: mymysql
  profiles:
    active: dev
  datasource:
    hikari:
      maximumPoolSize: 100 # 或者 100
      minimumIdle: 10
      idleTimeout: 30000
      maxLifetime: 1800000
      connectionTimeout: 300000


logging:
  level:
    root: INFO
    xyz.lidaning: INFO
    xyz.lidaning.random: ERROR